config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jobs#index'
  mount ActionCable.server => '/cable'
  patch '/auth' => 'admin/dashboard#auth', as: :auth

  get :shooting, to: 'jobs#shooting'
  get :network, to: 'chatrooms#network'
  get :hire, to: 'submissions#hire'

  namespace :admin do
    resources :dashboard, only: [:create, :destroy, :index, :auth]
  end

  resources :search do
    collection do
      get :autocomplete
      get :results
    end
  end

  resources :jobs, shallow: true do
    get :jobs_posted
    resources :submissions, only: [:create, :destroy, :index], as: :applications
  end

  resources :users, only: [:new, :create, :edit, :update] do
    get :profile
    resources :submissions, only: [:index, :hire], as: :applications
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :direct_messages, only: [:show]

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  devise_for :users, controllers: {sessions: "sessions"}

  resources :friendships, only: [:create, :update, :destroy]

  match "auth/facebook/callback/", to: "sessions#create", via: [:get, :post]
  match "auth/failure", to: redirect("/"), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy

  scope :public_channels, ->{ where(direct_message: false) }
  scope :direct_messages, ->{ where(direct_message: true) }

  def self.direct_message_for_users(users)
    user_ids = users.map(&:id).sort
    name = "DM:#{user_ids.join(":")}"

    if chatroom = direct_messages.where(name: name).first
      chatroom
    else
      # create a new chatroom
      chatroom = new(name: name, direct_message: true)
      chatroom.users = users
      chatroom.save
      chatroom
    end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  def network
    if current_user && current_user.friends
      @friends = current_user.friends
      @chatrooms = Chatroom.public_channels
    end
  end

  def index
    @chatrooms = Chatroom.public_channels
  end

  def show
    if current_user.friends
      @friends = current_user.friends
    end
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
    @chatrooms = Chatroom.public_channels
  end

  def new
    @chatroom = Chatroom.new
  end

  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_chat_module.html.erb
<div class="fluid-container sidechat" >
  <div class="col-sm-6" >
    <!-- style="position: fixed; top: 70px; left: 0;" -->
    <% if user_signed_in? %>
    <% if current_user.requested_friendships %>
    <div class="panel panel-default">
      <div class="panel-body">
      <h5>Public Chatrooms</h5>
      <ul>
        <% current_user.chatrooms.public_channels.each do |chatroom| %>
          <%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %>
        <% end %>
      </ul>
    </div>
    </div>
    <%end%>

      <% if @friends %>
      <div class="panel panel-default">
      <div class="panel-body">
      <h5>Messages</h5>
      <ul>
        <% @friends.each do |user| %>
          <li><%= link_to user.full_name, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %></li>
        <% end %>
      </ul>
      <% end %>
    <% end %>
  </div>
  </div>
</div>
</div>

app/views/chatrooms/_form.html.erb
<%= simple_form_for(@chatroom) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
<h1>Chatrooms</h1>
<hr>
<%= link_to 'New Chatroom', new_chatroom_path, type:"button", class:"btn-sm btn-info" %>
<br>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td><%= link_to 'View', chatroom, type:"button", class:"btn-sm btn-info" %></td>
        <!-- <td><%# link_to 'Edit', edit_chatroom_path(chatroom) %></td> -->
        <!-- <td><%# link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        <td><%= link_to "Join", chatroom_chatroom_users_path(chatroom), method: :post, type:"button", class:"btn-sm btn-info" %></td>
        <td><%= link_to "Leave", chatroom_chatroom_users_path(chatroom), method: :delete, type:"button", class:"btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/chatrooms/network.html.erb
<link href="/assets/network.scss" media="screen" rel="stylesheet" />

<%if user_signed_in? == false || current_user.is_auth  == false  %>

  <%= render :partial => 'layouts/unauthorized' %>

<% else %>

<div class="container">
<div class="row">

<div class="fluid-container sidechat" >
  <div class="col-sm-4" >
    <div class="panel panel-default">
      <div class="panel-body">
      <h4><%= link_to "Public Chatrooms", chatrooms_path %></h4>
      <hr>
      <table class="table">
        <% @chatrooms.each do |chatroom| %>
          <tr>
            <td><%= chatroom.name %></td>
            <td><%= link_to 'View', chatroom, type:"button", class:"btn-sm btn-info" %></td>
            <td><%= link_to "Join", chatroom_chatroom_users_path(chatroom), method: :post, type:"button", class:"btn-sm btn-info" %></td>
          </tr>
        <% end %>
      </table>
    </div>
    </div>

      <% if @friends %>
      <div class="panel panel-default">
      <div class="panel-body">
      <h4>Messages</h4>
      <hr>
      <ul>
        <% @friends.each do |user| %>
          <li><%= link_to user.full_name, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  </div>
</div>
</div>

<div class="col-sm-8">
<% if current_user.requested_friendships %>
<div class="panel panel-default">
  <div class="panel-body">
    <h4>Friend Requests</h4>
    <hr>
    <ul>
      <% current_user.requested_friendships.each do |request| %>
        <li>
          <% friendship = Friendship.find_by(user_id: request.id, friend_id: current_user.id) %>
          <%= link_to request.full_name, user_profile_path(request.id) %>
          <%= link_to "Accept",  friendship_path(id: friendship.id), method: "put", type:"button", class:"btn-sm btn-info" %>
          <%= link_to "Decline", friendship_path(id: friendship.id), method: :delete, type:"button", class:"btn-sm btn-danger" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<% if current_user.friends %>
  <div class="panel panel-default">
    <div class="panel-body">
    <h4>My Friends</h4>
    <hr>
    <ul>
      <% @friends.each do |f| %>
      <li>
          <%= link_to f.full_name, user_profile_path(f.id) %>
      </li>
      <% end %>
    </ul>
  </div>
  </div>
<% end %>
</div>



</div>
</div>

<% end %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<div class="panel panel-default container">
  <div class="panel-body row">

    <h2>Chatroom: <%= @chatroom.name %> </h2>
    <hr>

    <div class="col-sm-4" style="float:right; width: 400px">
      <h4><%= link_to "Public Chatrooms", chatrooms_path %></h4>
      <hr>
      <table class="table">
        <% @chatrooms.each do |chatroom| %>
          <tr>
            <td><%= chatroom.name %></td>
            <td><%= link_to 'View', chatroom, type:"button", class:"btn-sm btn-info" %></td>
            <td><%= link_to "Join", chatroom_chatroom_users_path(chatroom), method: :post, type:"button", class:"btn-sm btn-info" %></td>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="col-sm-4"style="float: left;
    clear: left;" >

      <div data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>' class='messages'>
        <% @chatroom.messages.each do |message| %>

          <%= render message %>
        <% end %>
      </div>
      <hr>
      <div>
      <%= form_for [@chatroom, Message.new] do |f| %>
        <%= f.text_area :body, rows: 1, class: "form-control", autofocus: true %>
      <% end %>
      </div>
    </div>


  </div>
</div>