config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jobs#index'
  mount ActionCable.server => '/cable'
  patch '/auth' => 'admin/dashboard#auth', as: :auth

  get :shooting, to: 'jobs#shooting'
  get :network, to: 'chatrooms#network'
  get :hire, to: 'submissions#hire'

  namespace :admin do
    resources :dashboard, only: [:create, :destroy, :index, :auth]
  end

  resources :search do
    collection do
      get :autocomplete
      get :results
    end
  end

  resources :jobs, shallow: true do
    get :jobs_posted
    resources :submissions, only: [:create, :destroy, :index], as: :applications
  end

  resources :users, only: [:new, :create, :edit, :update] do
    get :profile
    resources :submissions, only: [:index, :hire], as: :applications
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :direct_messages, only: [:show]

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  devise_for :users, controllers: {sessions: "sessions"}

  resources :friendships, only: [:create, :update, :destroy]

  match "auth/facebook/callback/", to: "sessions#create", via: [:get, :post]
  match "auth/failure", to: redirect("/"), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/job.rb
class Job < ApplicationRecord
  include AASM

  belongs_to :user
  has_many :applications, dependent: :nullify
  scope :reversed, -> { order 'created_at DESC' }

  searchkick text_start: [:title, :show], suggest: [:title, :show]

  validates(:title, { presence: { message: 'must be given!' },
                    uniqueness: true })

 geocoded_by :address
 after_validation :geocode

 aasm do
    state :Open, initial: true
    state :Filled

    state :Open do
      validates(:title, presence: true, length: { minimum: 3})
    end

    event :fill do
      transitions from: :Open, to: :Filled
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action(:find_job, { only: [:show, :edit, :destroy, :update] })
  before_action :authorize, only: [:edit, :destroy, :update]

  def new
    @job = Job.new
  end

  def create
    @job  = Job.new(job_params)
    @job.user = current_user
    if @job.save
      flash[:notice] = 'Job created successfully'
      redirect_to job_path(@job)
    else
      flash.now[:alert] = 'Please fix errors below'
      render :new
    end
  end

  def show
    @application = Application.new
  end

  def index
    @jobs = Job.all
    @jobs = Job.reversed
  end

  def jobs_posted
    @user = User.find(current_user)
    @jobs = Job.where(user_id: current_user)
  end

  def edit
  end

  def update
    #@question.slug = nil
    if @job.update job_params
      redirect_to job_path(@job), notice: 'Job updated!'
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_path, notice: 'Job deleted!'
  end

  def shooting
  end

  private

  def job_params
    params.require(:job).permit([:title,
                                :description,
                                :address,
                                :when,
                                :show,
                                :tcp,
                                :car,
                                :created_at])
  end

  def find_job
    @job = Job.find params[:id]
  end

  def authorize
    if cannot?(:manage, @job)
      redirect_to root_path, alert: 'Not authorized!'
    end
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :when %>
  <%= f.input :show %>
  <%= f.input :tcp %>
  <%= f.input :car %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/jobs/_notifications.html.erb
<div id="notifications">
</div>

app/views/jobs/index.html.erb
<%if user_signed_in? == false || current_user.is_auth  == false  %>

  <%= render :partial => 'layouts/unauthorized' %>

<% elsif @jobs.length != 0 %>

<div class="panel panel-default">
  <div class="panel-body">

    <h1>All Jobs</h1>
    <hr>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>When</th>
          <th>Show</th>
          <th>Poster</th>
          <th>Status</th>
        </tr>
      </thead>

      <tbody>
        <% @jobs.each do |j| %>
          <tr>
            <td><%= link_to j.title, job_path(j) %></td>
            <td><%= j.description %></td>
            <td><%= j.when.in_time_zone("Pacific Time (US & Canada)").to_formatted_s(:long_ordinal) %></td>
            <td><%= j.show %></td>
            <% if j.user_id %>
              <td><%= link_to User.find(j.user_id).full_name, user_profile_path(j.user_id) %></td>
              <% else %>
              <td></td>
            <% end %>
            <td><%= j.aasm_state %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% end %>

app/views/jobs/jobs_posted.html.erb
<%if user_signed_in? == false || current_user.is_auth  == false  %>
  <%= render :partial => 'layouts/unauthorized' %>
<% else %>
  <div class="panel panel-default">
    <div class="panel-body">
    <h1>Jobs Posted</h1>
    <hr>
    <% @jobs.each do |j| %>
      <h3 ><%= link_to j.title, j %></h3>
      <h4 ><%= j.description %></h4>
      <br>
      <hr>
    <% end %>
    </div>
  </div>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job Post</h1>

<%if user_signed_in? == false || current_user.is_auth  == false  %>
  <%= render :partial => 'layouts/unauthorized' %>
<% else %>
  <%= render 'form' %>
<% end %>

app/views/jobs/shooting.html.erb
<%  require 'mechanize'
mechanize = Mechanize.new
page = mechanize.get('http://www.whatsfilming.ca/inproduction')%>
<% table_length = page.css('tr').length - 1%>

<div class="panel panel-default">
  <div class="panel-body">

    <h1 class="page-header">What's Shooting</h1>
    <p>There are <%= table_length %> movies and TV shows currently filming in British Columbia.</p>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th>Filming Dates</th>
          <th>Sign Code</th>
          <th>Notable Cast</th>
        </tr>
      </thead>
      <tbody>
        <% table_length.times do |tr| %>
        <tr>
          <% row = page.css('tr')[tr] %>
          <% 5.times do |x| %>
          <% item = row.css('td')[x] %>
          <% if item == nil %>
            <td></td>
          <% else %>
            <td><%= item.text %></td>
          <% end %>
        <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/jobs/show.html.erb
<%if user_signed_in? == false || current_user.is_auth  == false  %>
  <%= render :partial => 'layouts/unauthorized' %>
<% else %>
<div class="panel panel-default">
  <div class="panel-body">

<h1><%= @job.title %></h1>
<hr>
<h4><small><%= @job.description %></small></h4>
<h4><small>Crew call: <%= @job.when.in_time_zone("Pacific Time (US & Canada)").to_formatted_s(:long_ordinal) %></small></h4>
<h4><small>Poster: <%= link_to @job.user.full_name, user_profile_path(@job.user) %></small></h4>
<h4><small>Status: <%= @job.aasm_state %></small></h4>
<h6><small>Posted At: <%= @job.updated_at.in_time_zone("Pacific Time (US & Canada)").to_formatted_s(:long_ordinal) %></small></h6>
<hr>


<% if @job.address %>
  <div style='width: 800px;'>
   <div id="map" style='width: 800px; height: 400px;'></div>
  </div>

  <script>
   handler = Gmaps.build('Google');
   handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers([
     {
       "lat": <%= @job.latitude %>,
       "lng": <%= @job.longitude %>,
       "infowindow": "<%= @job.title %>"
     }
   ]);
   handler.bounds.extendWith(markers);
   handler.fitMapToBounds();
   handler.getMap().setZoom(18);
   });
  </script>
<% end %>
<br>
<% if can?(:manage, @job) %>
  <div>
    <%= link_to 'Delete', job_path(@job),
                          method: :delete,
                          data: { confirm: 'Are you sure?' },
                          type:"button",
                          class:"btn-sm btn-danger" %>
    <%= link_to 'Edit', edit_job_path(@job), type:"button", class:"btn-sm btn-info" %>
  </div>

  <hr>
  <h2>Applications</h2>
  <% @job.applications.each do |app| %>
    <%= app.body %>
    <h5>Applicant: <%= link_to app.user.full_name, user_profile_path(app.user) %></h5>
    <h6>Posted At: <%= @job.updated_at.in_time_zone("Pacific Time (US & Canada)").to_formatted_s(:long_ordinal) %></h6>
    <%= link_to 'Delete', application_path(app) ,
                          method: :delete,
                          data: { confirm: 'Are you sure? '},
                          type:"button",
                          class:"btn-sm btn-danger" %>
    <%= link_to 'Hire', hire_path(app) , type:"button", class:"btn-sm btn-info" %>
    <hr>
  <% end %>

<% elsif @job.aasm_state != 'filled' %>
<hr>
  <h3>Apply</h3>
  <%= simple_form_for [@job, @application] do |f| %>
  <%= f.input :body, label: false, hint: 'at least 5 characters' %>
  <%= f.submit class: 'btn btn-primary' %>
  <% end %>
<% end %>
</div>
</div>
<% end %>