config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jobs#index'
  mount ActionCable.server => '/cable'
  patch '/auth' => 'admin/dashboard#auth', as: :auth

  get :shooting, to: 'jobs#shooting'
  get :network, to: 'chatrooms#network'
  get :hire, to: 'submissions#hire'

  namespace :admin do
    resources :dashboard, only: [:create, :destroy, :index, :auth]
  end

  resources :search do
    collection do
      get :autocomplete
      get :results
    end
  end

  resources :jobs, shallow: true do
    get :jobs_posted
    resources :submissions, only: [:create, :destroy, :index], as: :applications
  end

  resources :users, only: [:new, :create, :edit, :update] do
    get :profile
    resources :submissions, only: [:index, :hire], as: :applications
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :direct_messages, only: [:show]

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  devise_for :users, controllers: {sessions: "sessions"}

  resources :friendships, only: [:create, :update, :destroy]

  match "auth/facebook/callback/", to: "sessions#create", via: [:get, :post]
  match "auth/failure", to: redirect("/"), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  searchkick text_start: [:first_name, :last_name]

  has_many :notifications, foreign_key: :recipient_id

  has_many :jobs, dependent: :nullify

  has_many :applications, dependent: :destroy
  has_many :jobs_applied, through: :applications, source: :job

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages

  has_many :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :active_friends, -> { where(friendships: { accepted: true}) }, through: :friendships, source: :friend
  has_many :received_friends, -> { where(friendships: { accepted: true}) }, through: :received_friendships, source: :user

  has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
  has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user


  def friends
    active_friends | received_friends
  end


  def pending
    pending_friends | requested_friendships
  end



  before_validation :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: true,
                    format: VALID_EMAIL_REGEX,
                    unless: :from_omniauth?

  def full_name
    "#{first_name} #{last_name}".strip.titleize
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.email = auth.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.password = SecureRandom.hex(16)
      user.save!
    end
  end

  def self.authenticate (email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
    else
        nil
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def from_omniauth?
    uid.present? && provider.present?
  end

  def downcase_email
    self.email&.downcase!
  end
end

# has_many :friendships
# has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
# has_many :active_friends, -> { where(friendships: { accepted: true}) }, through: :friendships, source: :friend
# has_many :received_friends, -> { where(friendships: { accepted: true}) }, through: :received_friendships, source: :user
# has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
# has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json, only: [:search]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Account created successfully!'
    else
      render :new
    end
  end

  def profile
    @user = User.find(params[:user_id])
    @jobs = Job.where(user_id: current_user)
  end

  def edit
    @user = current_user
  end

  def update
    if @user.update user_params
      redirect_to user_profile_path(@user), notice: 'Job updated!'
    else
      render :edit
    end
  end

  def search
    @users = User.search(params[:query])
    if request.xhr?
      render :json => @users.to_json
    else
      @user = current_user
      render :profile
    end
  end


  private

  def user_params
    user_params = params.require(:user).permit(:first_name,
                                               :last_name,
                                               :email,
                                               :password,
                                               :password_confirmation,
                                               :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= @user.errors.full_messages.join(', ') %>
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :bio %>
  <%= f.input :experience %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :image %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <h1>Edit User</h1>
    <hr>
    <%= render 'form' %>

  </div>
</div>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <h1>Sign Up</h1>
    <hr>
    <%= render 'form' %>

  </div>
</div>

app/views/users/profile.html.erb
<%if user_signed_in? == false || current_user.is_auth  == false  %>
  <%= render :partial => 'layouts/unauthorized' %>

<% else %>

  <div class="panel panel-default">

    <div class="panel-body">
      <h1><%= @user.full_name %></h1>
      <hr>
      <%= image_tag @user.image.url(:thumb) if @user.image.present? %>
      <p><strong>About Me:</strong> <%= @user.bio %></p>
      <p><strong>My Experience:</strong> <%= @user.experience %></p>
      <h5>Reach Me At: <%= @user.phone %><%= @user.email %></h5>
      <hr>

      <%= link_to "Chat", direct_message_path(@user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, @user]).id }, type:"button", class:"btn-sm btn-info" %>

      <% friendship =
        current_user.friendships.where(friend_id: @user).limit(1).first %>
      <% received_friendship =
      current_user.received_friendships.where(user_id: @user).limit(1).first %>

      <% if friendship %>
        <% if friendship.accepted %>
          <%= link_to "Unfriend",
          friendship_path(id: friendship.id), method: :delete, type:"button", class:"btn-sm btn-danger" %>
        <% else %>
          <%= link_to "Cancel Friend Request",
          friendship_path(id: friendship.id), method: :delete, type:"button", class:"btn-sm btn-danger" %>
        <% end %>

      <% elsif received_friendship %>
        <% if received_friendship.accepted %>
          <%= link_to "Unfriend",
          friendship_path(id: received_friendship.id), method: :delete, type:"button", class:"btn-sm btn-danger" %>
        <% else %>
          <%= link_to "Accept Friend Request",
          friendship_path(id: received_friendship.id), method: "put", type:"button", class:"btn-sm btn-info" %>
          |
          <%= link_to "Reject Friend Request",
          friendship_path(id: received_friendship.id), method: :delete, type:"button", class:"btn-sm btn-danger" %>
        <% end %>

      <% elsif @user != current_user %>
        <%= link_to "Add Friend", friendships_path(friend_id: @user), method: :post, type:"button", class:"btn-sm btn-info" %>
      <% end %>


      <% if current_user.is_admin && @user.is_admin == false %>
          <%= link_to 'Make Admin', admin_dashboard_index_path(:user_id => @user.id), method: :post, type:"button", class:"btn-sm btn-info" %>
        <% elsif current_user.is_admin && @user.is_admin == true %>
          <%= link_to 'Undo Admin', admin_dashboard_path(:id => @user.id), method: :delete, type:"button", class:"btn-sm btn-danger" %>
      <% end %>

      <% if current_user == @user %>
        <%= link_to 'Edit Profile', edit_user_path(:id => @user.id), type:"button", class:"btn-sm btn-info" %>
      <% end %>

    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-body">

      <% if @jobs %>
      <h3>Jobs Posted: </h3>
      <hr>
        <% @jobs.each do |j| %>
          <h4 ><%= link_to j.title, j %></h4>
          <h5 ><%= j.description %></h5>
          <h5 >Status: <%= j.aasm_state %></h5>
          <br>
          <hr>
        <% end %>
      <% end %>

    </div>
  </div>

<% end %>