config/routes.rb
Rails.application.routes.draw do
  resources :chatrooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jobs#index'
  mount ActionCable.server => '/cable'
  patch '/auth' => 'admin/dashboard#auth', as: :auth

  get :shooting, to: 'jobs#shooting'
  get :network, to: 'chatrooms#network'
  get :hire, to: 'submissions#hire'

  namespace :admin do
    resources :dashboard, only: [:create, :destroy, :index, :auth]
  end

  resources :search do
    collection do
      get :autocomplete
      get :results
    end
  end

  resources :jobs, shallow: true do
    get :jobs_posted
    resources :submissions, only: [:create, :destroy, :index], as: :applications
  end

  resources :users, only: [:new, :create, :edit, :update] do
    get :profile
    resources :submissions, only: [:index, :hire], as: :applications
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :direct_messages, only: [:show]

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  devise_for :users, controllers: {sessions: "sessions"}

  resources :friendships, only: [:create, :update, :destroy]

  match "auth/facebook/callback/", to: "sessions#create", via: [:get, :post]
  match "auth/failure", to: redirect("/"), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is_admin?
      can :manage, :all
    end

    can :manage, Job do |j|
      j.user == user
    end

    cannot :manage, Job do |j|
      user != j.user
    end

    if user.is_auth?
      can [:read], [Job, Application, Connection]
    end

    if user.is_auth == false
      cannot [:read], [Job, Application, Connection]
    end
    #
    # cannot :like, Question do |q|
    #   user == q.user
    # end
    #
    # can :like, Question do |q|
    #   user != q.user
    # end
  end
end

app/models/application.rb
class Application < ApplicationRecord
  include AASM
  belongs_to :user
  belongs_to :job

  aasm do
     state :Submitted, initial: true
     state :Hired

     state :Submitted do
       validates(:body, presence: true, length: { minimum: 3})
     end

     event :accept do
       transitions from: :Submitted, to: :Hired
     end
   end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy

  scope :public_channels, ->{ where(direct_message: false) }
  scope :direct_messages, ->{ where(direct_message: true) }

  def self.direct_message_for_users(users)
    user_ids = users.map(&:id).sort
    name = "DM:#{user_ids.join(":")}"

    if chatroom = direct_messages.where(name: name).first
      chatroom
    else
      # create a new chatroom
      chatroom = new(name: name, direct_message: true)
      chatroom.users = users
      chatroom.save
      chatroom
    end
  end
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user
  belongs_to :connection, :class_name => 'User', :foreign_key =>'connection_id'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/job.rb
class Job < ApplicationRecord
  include AASM

  belongs_to :user
  has_many :applications, dependent: :nullify
  scope :reversed, -> { order 'created_at DESC' }

  searchkick text_start: [:title, :show], suggest: [:title, :show]

  validates(:title, { presence: { message: 'must be given!' },
                    uniqueness: true })

 geocoded_by :address
 after_validation :geocode

 aasm do
    state :Open, initial: true
    state :Filled

    state :Open do
      validates(:title, presence: true, length: { minimum: 3})
    end

    event :fill do
      transitions from: :Open, to: :Filled
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  #belongs_to :notifiable, polymorphic: true

  scope :unread, ->{ where(read_at: nil) }
  scope :recent, ->{ order(created_at: :desc).limit(5) }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  searchkick text_start: [:first_name, :last_name]

  has_many :notifications, foreign_key: :recipient_id

  has_many :jobs, dependent: :nullify

  has_many :applications, dependent: :destroy
  has_many :jobs_applied, through: :applications, source: :job

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages

  has_many :friendships
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"

  has_many :active_friends, -> { where(friendships: { accepted: true}) }, through: :friendships, source: :friend
  has_many :received_friends, -> { where(friendships: { accepted: true}) }, through: :received_friendships, source: :user

  has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
  has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user


  def friends
    active_friends | received_friends
  end


  def pending
    pending_friends | requested_friendships
  end



  before_validation :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: true,
                    format: VALID_EMAIL_REGEX,
                    unless: :from_omniauth?

  def full_name
    "#{first_name} #{last_name}".strip.titleize
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.email = auth.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.password = SecureRandom.hex(16)
      user.save!
    end
  end

  def self.authenticate (email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
    else
        nil
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def from_omniauth?
    uid.present? && provider.present?
  end

  def downcase_email
    self.email&.downcase!
  end
end

# has_many :friendships
# has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
# has_many :active_friends, -> { where(friendships: { accepted: true}) }, through: :friendships, source: :friend
# has_many :received_friends, -> { where(friendships: { accepted: true}) }, through: :received_friendships, source: :user
# has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
# has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_unauthorized.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <div class="jumbotron">
      <h1><small>You are not authorized to view this page.</small></h1>
      <p>If your membership is pending, we will notify you when you're good to go.<p>
      <p><%= link_to "Sign in", new_user_session_path, type:"button", class:"btn btn-primary btn-lg" %></p>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Shoot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyBu0omosr68RmPFcMsx6-PfD9heRkuupqE"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

    <% if user_signed_in? %>
      <%= tag :meta, name: "current-user", data: {id: current_user.id } %>
    <% end %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: "navbar-brand nav-item active" do %>
        <img src="../assets/images/logo.jpg">
      <% end %>
    </div>

     <div class="collapse navbar-collapse" >

     <ul class="nav navbar-nav navbar-right mr-auto">
       <% if user_signed_in? %>
         <%#yield :right_nav %>
        <li class='active'><%= active_link_to 'Hiring Board', jobs_path, :class => 'nav-link' %></li>
        <li><%= link_to 'Network', network_path %></li>

        <li class="nav-item btn-group" data-behavior="notifications">
          <a class="dropdown-toggle nav-link" type="button" data-behavior="notifications-link"
            id="dropdownMenu1"   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon "bell" %> <span data-behavior="unread-count"></span>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items">
          </div>
        </li>

         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name %> <span class="caret"></span></a>
           <ul class="dropdown-menu">
             <li><%= link_to 'Post a Job', new_job_path %></li>
             <li role="separator" class="divider"></li>
              <% if user_signed_in? && current_user.is_admin %>
                <li><%= link_to 'Admin', admin_dashboard_index_path %></li>
              <% end %>
              <li><%= link_to 'Profile', user_profile_path(current_user) %></li>
              <li><%= link_to 'My Applications', user_applications_path(current_user) %></li>
              <li><%= link_to 'Jobs Posted', job_jobs_posted_path(current_user) %></li>
              <li><%= link_to "Chatrooms", chatrooms_path %></li>
              <li><%= link_to 'What\'s Shooting', shooting_path %></li>
             <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
           </ul>
           </li>
         <% else %>
           <li><%= link_to 'Sign Up', new_user_path %></li>
           <li><%= link_to 'Sign In', new_user_session_path %></li>
         <% end %>
       </ul>
     </div>
   </div>
  </nav>

    <% if notice || alert %>
      <div class="alert alert-info" role="alert">
        <%= notice || alert %>
      </div>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div>

</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Shoot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyBu0omosr68RmPFcMsx6-PfD9heRkuupqE"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <% if user_signed_in? %>
    <%= tag :meta, name: "current-user", data: {id: current_user.id } %>
    <% end %>
  </head>

  <body style="background-image:url(../../assets/polaroid.png)">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to root_path, class: "navbar-brand" do %>
          <img src="../../assets/logo.jpg" alt="Let's Shoot" id="logo">
          <% end %>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
          </ul>

          <ul class="nav navbar-nav">
            <li><%= link_to 'Hiring Board', jobs_path %></li>
            <li><%= link_to 'Network', network_path %></li>
          </ul>

          <%= form_tag results_search_index_path, method: :get, class: "navbar-form navbar-right search" do %>
            <%= text_field_tag :s, nil, placeholder: "Search" %>
            <button type="submit" class="btn btn-sm btn-default">Submit</button>
          <% end %>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li class="nav-item btn-group" data-behavior="notifications">
              <a class="dropdown-toggle nav-link" type="button" data-behavior="notifications-link"
              id="dropdownMenu1"   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon "bell" %> <span data-behavior="unread-count"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items">
            </div>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Post a Job', new_job_path %></li>
              <li role="separator" class="divider"></li>
              <% if user_signed_in? && current_user.is_admin %>
              <li><%= link_to 'Admin', admin_dashboard_index_path %></li>
              <% end %>
              <li><%= link_to 'Profile', user_profile_path(current_user) %></li>
              <li><%= link_to 'My Applications', user_applications_path(current_user) %></li>
              <li><%= link_to 'Jobs Posted', job_jobs_posted_path(current_user) %></li>
              <li><%= link_to "Chatrooms", chatrooms_path %></li>
              <li><%= link_to 'What\'s Shooting', shooting_path %></li>
              <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
        </ul>

      </div>
    </div>
  </nav>

  <% if notice || alert %>
    <div class="alert alert-info" role="alert">
      <%= notice || alert %>
    </div>
  <% end %>

  <div class='container main-content'>
    <%= yield %>
  </div>

  </body>
</html>